create table offices (
    id         bigint generated by default as identity primary key,
    name       varchar(120)     not null,
    latitude   double precision not null,
    longitude  double precision not null
);

create table employees (
    id         bigint generated by default as identity primary key,
    name       varchar(120)     not null,
    gender     varchar(16)      not null,
    latitude   double precision not null,
    longitude  double precision not null,
    office_id  bigint           not null references offices (id)
);
create index idx_employees_office on employees (office_id);

create table route_plans (
    id               bigint generated by default as identity primary key,
    office_id        bigint                   not null references offices (id),
    shift_time       timestamp                not null,
    direction        varchar(8)               not null,
    cab_capacity     integer                  not null,
    max_ride_minutes integer                  not null,
    revision         integer                  not null,
    version          bigint                   not null,
    created_at       timestamp with time zone not null,
    updated_at       timestamp with time zone not null
);
create index idx_route_plans_office_shift on route_plans (office_id, shift_time);

create table cab_routes (
    id               bigint generated by default as identity primary key,
    plan_id          bigint           not null references route_plans (id) on delete cascade,
    cab_number       integer          not null,
    distance_km      double precision not null,
    max_ride_minutes double precision not null,
    escort_required  boolean          not null,
    office_time      timestamp        not null
);
create index idx_cab_routes_plan on cab_routes (plan_id);

-- Coordinates are copied onto the stop so a later change to an employee's home
-- address does not silently rewrite a plan that has already been issued.
create table route_stops (
    id            bigint generated by default as identity primary key,
    cab_id        bigint           not null references cab_routes (id) on delete cascade,
    employee_id   bigint           not null references employees (id),
    stop_sequence integer          not null,
    latitude      double precision not null,
    longitude     double precision not null,
    eta           timestamp        not null,
    ride_minutes  double precision not null
);
create index idx_route_stops_cab on route_stops (cab_id);
create index idx_route_stops_employee on route_stops (employee_id);
